global:
  imageRegistry: ""
  imagePullSecrets: []
  # - name: "image-pull-secret"

kubectl:
  image:
    registry: ""
    repository: mingys/ks-helm-executor
    tag: "v3.22.0-kubectl-v1.33.4"
    pullPolicy: IfNotPresent
  resources:
    limits:
      cpu: 1
      memory: 1024Mi
    requests:
      cpu: 20m
      memory: 100Mi
